name: Example Artifact Workflow
run-name: Example Artifact Workflow Run
on: 
  workflow_dispatch:
env: 
  name-artifact: example-artifact
  folder: artifact-example
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the runner
        run: ls -R

      - name: Generate a files
        run: |
          mkdir -p artifact-example
          echo "File 1" > ${{ env.folder }}/file1.txt
          echo "File 2" > ${{ env.folder }}/file2.txt
          echo "File 3" > ${{ env.folder }}/file3.txt
          echo "File 4" > ${{ env.folder }}/file4.txt

      - name: Upload a file
        uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          name:  ${{ env.name-artifact }}
          path: ./${{ env.folder }}
          retention-days: 2

      - name: List files in the artifact
        run: ls
      
      - name: Address to download the artifact
        run: |
          echo "${{ steps.upload-artifact.outputs.artifact-url }}"

  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name:  ${{ env.name-artifact }}
          
      - name: List files in the artifact
        run: ls
        
        