name: Working with Inputs
run-name: Working with Inputs, executado por ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        default: "dev"
        description: "Versão da nova release"
      card:
        type: number
        required: true
        description: "Número do card da tarefa"
      do_deploy:
        type: boolean
        required: true
        description: "Deseja fazer deploy?"
      environment:
        type: choice
        required: true
        description: "Ambiente de deploy"
        options:
          - dev
          - homolog
          - prod
jobs:
  valores_input:
    runs-on: ubuntu-latest
    steps:
      - name: Show All Contexts
        run: echo "${{toJson(inputs)}}"
      - name: Mostrando valores dos inputs
        run: |
          echo "Versão: ${{ inputs.version }}"
          echo "Número do card: ${{ inputs.card }}"
          echo "Fazer deploy: ${{ inputs.do_deploy }}"
          echo "Ambiente: ${{ inputs.environment }}"
